In [1]:
import pandas as pd

In [2]:
jobs = pd.read_csv("../data/fullsample.csv", nrows = 1000)
jobs.head(50)

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
0,30616928,RUNNING,2021-07-31T22:15:00,Unknown,2048Mn,0,10:04:00,67-22:14:22,1,1,production,0:0
1,30853133,COMPLETED,2021-08-06T11:36:09,2021-09-05T11:36:32,262144Mn,20604.62M,30-00:00:00,30-00:00:23,1,1,cgw-platypus,0:0
2,30858137,COMPLETED,2021-08-06T19:04:39,2021-09-05T19:04:53,204800Mn,57553.77M,30-00:00:00,30-00:00:14,1,32,cgw-tbi01,0:0
3,30935078,COMPLETED,2021-08-09T16:52:51,2021-09-07T20:52:55,65536Mn,20577.96M,29-04:00:00,29-04:00:04,1,8,cgw-platypus,0:0
4,31364111_2,COMPLETED,2021-08-17T07:45:07,2021-09-10T16:45:24,16384Mn,9733.43M,24-09:00:00,24-09:00:17,1,1,production,0:0
5,31364111_3,COMPLETED,2021-08-17T07:45:07,2021-09-06T16:17:34,16384Mn,9708.04M,24-09:00:00,20-08:32:27,1,1,production,0:0
6,31364111_4,COMPLETED,2021-08-17T07:45:07,2021-09-06T06:25:11,16384Mn,9785.61M,24-09:00:00,19-22:40:04,1,1,production,0:0
7,31364111_5,COMPLETED,2021-08-17T07:45:07,2021-09-06T10:05:33,16384Mn,9966.38M,24-09:00:00,20-02:20:26,1,1,production,0:0
8,31364111_6,COMPLETED,2021-08-17T07:45:07,2021-09-05T12:53:04,16384Mn,9684.02M,24-09:00:00,19-05:07:57,1,1,production,0:0
9,31364111_9,COMPLETED,2021-08-17T07:45:07,2021-09-06T09:10:13,16384Mn,9802.24M,24-09:00:00,20-01:25:06,1,1,production,0:0
10,31364111_10,COMPLETED,2021-08-17T07:45:07,2021-09-06T08:08:53,16384Mn,9697.47M,24-09:00:00,20-00:23:46,1,1,production,0:0
11,31364111_13,COMPLETED,2021-08-17T07:45:07,2021-09-05T22:42:38,16384Mn,9688.84M,24-09:00:00,19-14:57:31,1,1,production,0:0
12,31364111_14,COMPLETED,2021-08-17T07:45:07,2021-09-06T05:46:58,16384Mn,9669.09M,24-09:00:00,19-22:01:51,1,1,production,0:0
13,31364111_15,COMPLETED,2021-08-17T07:45:07,2021-09-07T00:57:05,16384Mn,9705.03M,24-09:00:00,20-17:11:58,1,1,production,0:0
14,31364111_16,COMPLETED,2021-08-17T07:45:07,2021-09-05T22:47:23,16384Mn,9847.77M,24-09:00:00,19-15:02:16,1,1,production,0:0
15,31364111_20,COMPLETED,2021-08-17T07:45:07,2021-09-06T11:03:58,16384Mn,9837.14M,24-09:00:00,20-03:18:51,1,1,production,0:0
16,31364111_22,COMPLETED,2021-08-17T07:45:07,2021-09-07T01:07:23,16384Mn,9767.92M,24-09:00:00,20-17:22:16,1,1,production,0:0
17,31375213,COMPLETED,2021-08-17T12:24:05,2021-09-03T04:24:09,768000Mn,469211.72M,16-16:00:00,16-16:00:04,1,10,cgw-platypus,0:0
18,31418105,NODE_FAIL,2021-08-19T10:09:50,2021-09-17T08:45:10,92160Mn,0,41-16:00:00,28-22:35:20,1,8,cgw-dougherty1,1:0
19,31462631,COMPLETED,2021-08-20T14:36:39,2021-09-03T14:36:58,512000Mn,66213.39M,14-00:00:00,14-00:00:19,1,24,production,0:0
20,31462632,COMPLETED,2021-08-20T14:36:39,2021-09-03T14:36:58,512000Mn,69560.74M,14-00:00:00,14-00:00:19,1,24,production,0:0
21,30796171,COMPLETED,2021-08-21T19:50:38,2021-09-04T13:50:55,251904Mn,243216.12M,13-18:00:00,13-18:00:17,1,16,production,0:0
22,31587567,COMPLETED,2021-08-23T11:21:53,2021-09-02T11:22:16,65536Mn,35830.86M,10-00:00:00,10-00:00:23,1,4,production,0:0
23,31364111_23,COMPLETED,2021-08-25T00:42:46,2021-09-16T23:57:20,16384Mn,10263.21M,24-09:00:00,22-23:14:34,1,1,production,0:0
24,31364111_7,COMPLETED,2021-08-25T00:42:46,2021-09-16T21:55:36,16384Mn,10149.74M,24-09:00:00,22-21:12:50,1,1,production,0:0
25,31364111_8,COMPLETED,2021-08-25T00:42:46,2021-09-16T18:49:44,16384Mn,10210.02M,24-09:00:00,22-18:06:58,1,1,production,0:0
26,31364111_24,COMPLETED,2021-08-25T00:42:46,2021-09-16T21:53:04,16384Mn,10111.25M,24-09:00:00,22-21:10:18,1,1,production,0:0
27,31364111_25,COMPLETED,2021-08-25T00:42:46,2021-09-16T15:35:39,16384Mn,10229.07M,24-09:00:00,22-14:52:53,1,1,production,0:0
28,31712333,COMPLETED,2021-08-26T09:52:09,2021-09-05T09:52:22,16384Mn,5534.91M,10-00:00:00,10-00:00:13,1,1,production,0:0
29,31714782,COMPLETED,2021-08-26T11:24:38,2021-09-04T15:24:58,131072Mn,54301.60M,9-04:00:00,9-04:00:20,1,2,cgw-platypus,0:0
30,31734297,COMPLETED,2021-08-27T11:41:53,2021-09-01T11:42:07,6144Mn,334.34M,5-00:00:00,5-00:00:14,1,1,pascal,0:0
31,31734302,COMPLETED,2021-08-27T11:42:53,2021-09-01T11:43:07,6144Mn,334.27M,5-00:00:00,5-00:00:14,1,1,pascal,0:0
32,31734305,COMPLETED,2021-08-27T11:42:53,2021-09-01T11:43:07,6144Mn,335.75M,5-00:00:00,5-00:00:14,1,1,pascal,0:0
33,31740395,COMPLETED,2021-08-27T16:55:22,2021-09-01T16:55:51,92160Mn,96.32M,5-00:00:00,5-00:00:29,1,8,cgw-dougherty1,0:0
34,31741417,COMPLETED,2021-08-27T17:51:36,2021-09-01T17:51:47,92160Mn,12562.29M,5-00:00:00,5-00:00:11,1,8,cgw-dougherty1,0:0
35,31747055,COMPLETED,2021-08-27T22:41:38,2021-09-01T22:42:05,6144Mn,334.11M,5-00:00:00,5-00:00:27,1,1,pascal,0:0
36,31750176,COMPLETED,2021-08-28T03:02:44,2021-09-03T00:55:23,30720Mn,13141.78M,8-02:20:00,5-21:52:39,1,32,production,0:0
37,31750955,COMPLETED,2021-08-28T08:04:58,2021-09-02T08:05:16,6144Mn,335.68M,5-00:00:00,5-00:00:18,1,1,pascal,0:0
38,31750956,COMPLETED,2021-08-28T08:05:11,2021-09-02T08:05:16,6144Mn,335.79M,5-00:00:00,5-00:00:05,1,1,pascal,0:0
39,31750959,COMPLETED,2021-08-28T08:05:59,2021-09-02T08:06:15,6144Mn,334.14M,5-00:00:00,5-00:00:16,1,1,pascal,0:0
40,31750960,COMPLETED,2021-08-28T08:06:17,2021-09-02T08:06:45,6144Mn,335.81M,5-00:00:00,5-00:00:28,1,1,pascal,0:0
41,31750961,COMPLETED,2021-08-28T08:06:34,2021-09-02T08:06:45,6144Mn,334.30M,5-00:00:00,5-00:00:11,1,1,pascal,0:0
42,31669402,CANCELLED,2021-08-28T10:53:59,2021-09-05T10:53:57,65536Mn,5229.75M,8-00:00:00,7-23:59:58,9,10,production,0:15
43,31752910,COMPLETED,2021-08-28T12:39:36,2021-09-01T19:52:26,24576Mn,271.75M,5-00:00:00,4-07:12:50,1,2,pascal,0:0
44,31752911,COMPLETED,2021-08-28T12:39:46,2021-09-01T17:16:39,24576Mn,269.61M,5-00:00:00,4-04:36:53,1,2,pascal,0:0
45,31752918,COMPLETED,2021-08-28T12:42:58,2021-09-02T12:43:27,24576Mn,272.30M,5-00:00:00,5-00:00:29,1,2,pascal,0:0
46,31753071,COMPLETED,2021-08-28T13:00:27,2021-09-02T13:00:29,6144Mn,334.99M,5-00:00:00,5-00:00:02,1,1,pascal,0:0
47,31753073,COMPLETED,2021-08-28T13:00:47,2021-09-02T13:00:59,6144Mn,333.81M,5-00:00:00,5-00:00:12,1,1,pascal,0:0
48,31753085,COMPLETED,2021-08-28T13:01:09,2021-09-02T13:01:29,6144Mn,334.00M,5-00:00:00,5-00:00:20,1,1,pascal,0:0
49,31756600,COMPLETED,2021-08-28T21:26:42,2021-09-02T21:26:59,6144Mn,334.15M,5-00:00:00,5-00:00:17,1,1,pascal,0:0

In [8]:
jobs = pd.read_csv("../data/fullsample.csv")

In [10]:
jobs.isna().sum()

JOBID        0
STATE        0
BEGIN        0
END          0
REQMEM       0
USEDMEM      0
REQTIME      0
USEDTIME     0
NODES        0
CPUS         0
PARTITION    0
EXITCODE     0
dtype: int64

In [11]:
jobs.isnull().sum()

JOBID        0
STATE        0
BEGIN        0
END          0
REQMEM       0
USEDMEM      0
REQTIME      0
USEDTIME     0
NODES        0
CPUS         0
PARTITION    0
EXITCODE     0
dtype: int64

In [13]:
jobs.duplicated().sum()

0

In [14]:
jobs.head()

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
0,30616928,RUNNING,2021-07-31T22:15:00,Unknown,2048Mn,0,10:04:00,67-22:14:22,1,1,production,0:0
1,30853133,COMPLETED,2021-08-06T11:36:09,2021-09-05T11:36:32,262144Mn,20604.62M,30-00:00:00,30-00:00:23,1,1,cgw-platypus,0:0
2,30858137,COMPLETED,2021-08-06T19:04:39,2021-09-05T19:04:53,204800Mn,57553.77M,30-00:00:00,30-00:00:14,1,32,cgw-tbi01,0:0
3,30935078,COMPLETED,2021-08-09T16:52:51,2021-09-07T20:52:55,65536Mn,20577.96M,29-04:00:00,29-04:00:04,1,8,cgw-platypus,0:0
4,31364111_2,COMPLETED,2021-08-17T07:45:07,2021-09-10T16:45:24,16384Mn,9733.43M,24-09:00:00,24-09:00:17,1,1,production,0:0

In [15]:
#different states in data
jobs['STATE'].value_counts()

STATE
COMPLETED              7375084
CANCELLED                 9055
FAILED                    3766
CANCELLED by 9201         1776
OUT_OF_MEMORY             1739
                        ...
CANCELLED by 891323          1
CANCELLED by 889553          1
CANCELLED by 793827          1
CANCELLED by 790983          1
CANCELLED by 907426          1
Name: count, Length: 145, dtype: int64

In [33]:
jobs[jobs['STATE'] == 'CANCELLED by 9201'].head(25)

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
125522,32033427,CANCELLED by 9201,2021-09-04T20:46:36,2021-09-04T20:46:36,186648Mn,0,2-00:00:00,00:00:00,1,32,nogpfs,0:0
146144,32045664,CANCELLED by 9201,2021-09-05T07:30:42,2021-09-05T07:30:42,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
170984,32033940,CANCELLED by 9201,2021-09-05T22:07:49,2021-09-05T22:07:49,186648Mn,0,2-00:00:00,00:00:00,1,32,nogpfs,0:0
290072,32162742,CANCELLED by 9201,2021-09-08T01:01:37,2021-09-08T01:01:39,3100Mn,0,2-00:00:00,00:00:02,1,2,pascal,0:0
306932,32161293,CANCELLED by 9201,2021-09-09T11:31:18,2021-09-09T11:31:18,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
306933,32164597,CANCELLED by 9201,2021-09-09T11:31:18,2021-09-09T11:31:18,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
306938,32165049,CANCELLED by 9201,2021-09-09T11:30:48,2021-09-09T11:30:48,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
306944,32128589,CANCELLED by 9201,2021-09-09T11:33:31,2021-09-09T11:33:31,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
306945,32161894,CANCELLED by 9201,2021-09-09T11:30:03,2021-09-09T11:30:03,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
306946,32176959,CANCELLED by 9201,2021-09-09T11:31:18,2021-09-09T11:31:18,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
306950,32191247,CANCELLED by 9201,2021-09-09T11:30:48,2021-09-09T11:30:48,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
306951,32194189,CANCELLED by 9201,2021-09-09T11:30:03,2021-09-09T11:30:03,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
306952,32195785,CANCELLED by 9201,2021-09-09T11:30:48,2021-09-09T11:30:48,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
306956,32177915,CANCELLED by 9201,2021-09-09T11:30:48,2021-09-09T11:30:48,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
307003,32144969,CANCELLED by 9201,2021-09-09T11:37:24,2021-09-09T11:37:24,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307004,32165054,CANCELLED by 9201,2021-09-09T11:38:37,2021-09-09T11:38:37,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307005,32172490,CANCELLED by 9201,2021-09-09T11:38:36,2021-09-09T11:38:36,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307006,32173351,CANCELLED by 9201,2021-09-09T11:40:18,2021-09-09T11:40:18,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307008,32187949,CANCELLED by 9201,2021-09-09T11:41:09,2021-09-09T11:41:09,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307009,32194250,CANCELLED by 9201,2021-09-09T11:38:37,2021-09-09T11:38:37,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307013,32141768,CANCELLED by 9201,2021-09-09T11:40:48,2021-09-09T11:40:48,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
307015,32165506,CANCELLED by 9201,2021-09-09T11:42:01,2021-09-09T11:42:01,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307016,32185511,CANCELLED by 9201,2021-09-09T11:42:25,2021-09-09T11:42:25,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0
307017,32196781,CANCELLED by 9201,2021-09-09T11:42:30,2021-09-09T11:42:30,28000Mn,0,2-00:00:00,00:00:00,1,4,production,0:0
307021,32173176,CANCELLED by 9201,2021-09-09T11:41:09,2021-09-09T11:41:09,5000Mn,0,2-00:00:00,00:00:00,1,1,production,0:0

In [18]:
jobs[jobs['STATE'] == 'CANCELLED by 889553']

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE
821137,32770642,CANCELLED by 889553,2021-09-23T22:46:19,2021-09-23T22:59:09,1024Mc,6.57M,00:30:00,00:12:50,1,1,production,0:9

In [27]:
#total abort/issue on serverside
(jobs['EXITCODE'].str[0:1] != '0').sum()

5951

In [31]:
#total abort/issue on clientsode
(jobs['EXITCODE'].str[2:3] != '0').sum()

5891

In [36]:
jobs['isSeverError'] = jobs['EXITCODE'].apply(lambda x : 1  if x[0:1] != '0' else 0)
jobs['isClientError'] = jobs['EXITCODE'].apply(lambda x : 1  if x[2:3] != '0' else 0)

In [40]:
jobs[jobs['isSeverError'] == 1]

,JOBID,STATE,BEGIN,END,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,isSeverError,isClientError
18,31418105,NODE_FAIL,2021-08-19T10:09:50,2021-09-17T08:45:10,92160Mn,0,41-16:00:00,28-22:35:20,1,8,cgw-dougherty1,1:0,1,0
31996,31934490,FAILED,2021-09-01T09:08:52,2021-09-01T09:24:08,92160Mn,65881.35M,3-08:00:00,00:15:16,1,1,maxwell,1:0,1,0
32031,31934552,FAILED,2021-09-01T09:20:33,2021-09-01T09:26:18,20480Mc,542.73M,3-00:00:00,00:05:45,2,40,production,121:0,1,1
32199,31934755,FAILED,2021-09-01T09:35:01,2021-09-01T15:37:14,20000Mn,13323.77M,1-08:00:00,06:02:13,1,1,production,1:0,1,0
32204,31934760,FAILED,2021-09-01T09:35:02,2021-09-01T13:07:26,20000Mn,10697.71M,1-08:00:00,03:32:24,1,1,production,1:0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7381940,25455788,FAILED,2020-10-30T00:26:40,2020-10-30T20:26:43,5120Mc,28869.91M,20:00:00,20:00:03,22,4,production,1:0,1,0
7387147,25467240,FAILED,2020-10-30T11:47:49,2020-10-30T11:47:59,20480Mn,0,04:00:00,00:00:10,1,1,pascal,127:0,1,1
7387598,25469985_10,FAILED,2020-10-30T13:46:33,2020-10-30T13:46:54,8192Mn,0,1-00:00:00,00:00:21,1,4,production,1:0,1,0
7387599,25469985_11,FAILED,2020-10-30T13:46:26,2020-10-30T13:46:37,8192Mn,11.43M,1-00:00:00,00:00:11,1,4,production,1:0,1,0
7387600,25469985_12,FAILED,2020-10-30T13:46:29,2020-10-30T13:46:37,8192Mn,0,1-00:00:00,00:00:08,1,4,production,1:0,1,0